CREATE TABLE IF NOT EXISTS ECOMMERCE_DB.STAGING.ORDERS_CLEANED (
    ORDER_ID            VARCHAR(50),
    CUSTOMER_ID         VARCHAR(50),
    CUSTOMER_NAME       VARCHAR(200),
    EMAIL               VARCHAR(200),
    PRODUCT_ID          VARCHAR(50),
    PRODUCT_NAME        VARCHAR(300),
    CATEGORY            VARCHAR(100),
    QUANTITY            INT,
    UNIT_PRICE          NUMBER(10,2),
    TOTAL_AMOUNT        NUMBER(12,2),
    ORDER_STATUS        VARCHAR(50),
    ORDER_DATE          DATE,
    SHIP_DATE           DATE,
    SHIP_COUNTRY        VARCHAR(100),
    PAYMENT_METHOD      VARCHAR(50),
    LOADED_AT           TIMESTAMP_LTZ,
    PROCESSED_AT        TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Cleaned and standardized orders from RAW layer';

--Verify table
DESCRIBE TABLE ECOMMERCE_DB.STAGING.ORDERS_CLEANED;