-- Phase 2, Step 6: Create Snowpipe
CREATE PIPE IF NOT EXISTS ECOMMERCE_DB.RAW.ORDERS_PIPE
  AUTO_INGEST = TRUE
  COMMENT = 'Auto-ingest pipe for order CSVs from S3'
AS
  COPY INTO ECOMMERCE_DB.RAW.ORDERS
  FROM @ECOMMERCE_DB.RAW.S3_ORDERS_STAGE
  FILE_FORMAT = ECOMMERCE_DB.RAW.CSV_FORMAT
  MATCH_BY_COLUMN_NAME = NONE;

  -- Get the SQS ARN for S3 notifications
  SHOW PIPES IN SCHEMA ECOMMERCE_DB.RAW;