-- Phase 2, Step 8: Test End-to-End Ingestion
SELECT SYSTEM$PIPE_STATUS('ECOMMERCE_DB.RAW.ORDERS_PIPE');

LIST @ECOMMERCE_DB.RAW.S3_ORDERS_STAGE;

-- Manually trigger the first load
ALTER PIPE ECOMMERCE_DB.RAW.ORDERS_PIPE REFRESH;

--after few minutes waiting, checking my table
SELECT COUNT(*) FROM ECOMMERCE_DB.RAW.ORDERS;


COPY INTO ECOMMERCE_DB.RAW.ORDERS (ORDER_ID, CUSTOMER_ID, CUSTOMER_NAME, EMAIL, PRODUCT_ID, PRODUCT_NAME, CATEGORY, QUANTITY, UNIT_PRICE, ORDER_STATUS, ORDER_DATE, SHIP_DATE, SHIP_COUNTRY, PAYMENT_METHOD)
FROM @ECOMMERCE_DB.RAW.S3_ORDERS_STAGE
FILE_FORMAT = ECOMMERCE_DB.RAW.CSV_FORMAT
FORCE = TRUE;



CREATE OR REPLACE PIPE ECOMMERCE_DB.RAW.ORDERS_PIPE
  AUTO_INGEST = TRUE
  COMMENT = 'Auto-ingest pipe for order CSVs from S3'
AS
  COPY INTO ECOMMERCE_DB.RAW.ORDERS (ORDER_ID, CUSTOMER_ID, CUSTOMER_NAME, EMAIL, PRODUCT_ID, PRODUCT_NAME, CATEGORY, QUANTITY, UNIT_PRICE, ORDER_STATUS, ORDER_DATE, SHIP_DATE, SHIP_COUNTRY, PAYMENT_METHOD)
  FROM @ECOMMERCE_DB.RAW.S3_ORDERS_STAGE
  FILE_FORMAT = ECOMMERCE_DB.RAW.CSV_FORMAT;



SHOW PIPES IN SCHEMA ECOMMERCE_DB.RAW;

