--CREATE TASK1:

CREATE TASK IF NOT EXISTS ECOMMERCE_DB.RAW.TASK_RAW_TO_STAGING
  WAREHOUSE = ECOMMERCE_WH
  SCHEDULE = '5 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('ECOMMERCE_DB.RAW.ORDERS_STREAM')
AS
  INSERT INTO ECOMMERCE_DB.STAGING.ORDERS_CLEANED (
      ORDER_ID, CUSTOMER_ID, CUSTOMER_NAME, EMAIL, PRODUCT_ID, PRODUCT_NAME,
      CATEGORY, QUANTITY, UNIT_PRICE, TOTAL_AMOUNT, ORDER_STATUS,
      ORDER_DATE, SHIP_DATE, SHIP_COUNTRY, PAYMENT_METHOD, LOADED_AT
  )
  SELECT
      TRIM(ORDER_ID),
      TRIM(CUSTOMER_ID),
      TRIM(CUSTOMER_NAME),
      LOWER(TRIM(EMAIL)),
      TRIM(PRODUCT_ID),
      TRIM(PRODUCT_NAME),
      UPPER(TRIM(CATEGORY)),
      QUANTITY,
      UNIT_PRICE,
      QUANTITY * UNIT_PRICE,
      UPPER(TRIM(ORDER_STATUS)),
      ORDER_DATE,
      SHIP_DATE,
      UPPER(TRIM(SHIP_COUNTRY)),
      UPPER(TRIM(PAYMENT_METHOD)),
      LOADED_AT
  FROM ECOMMERCE_DB.RAW.ORDERS_STREAM;

--Verify it exists:
SHOW TASKS IN SCHEMA ECOMMERCE_DB.RAW;
  