CREATE STREAM IF NOT EXISTS ECOMMERCE_DB.RAW.ORDERS_STREAM

ON TABLE ECOMMERCE_DB.RAW.ORDERS
APPEND_ONLY = TRUE
COMMENT = "Tracks new rows inserted into RAW.ORDERS by snowpipe"

--Verify it was created:
SHOW STREAMS IN SCHEMA ECOMMERCE_DB.RAW;

--test the stream — insert a row:
INSERT INTO ECOMMERCE_DB.RAW.ORDERS (ORDER_ID, CUSTOMER_ID, CUSTOMER_NAME, EMAIL, PRODUCT_ID, PRODUCT_NAME, CATEGORY, QUANTITY, UNIT_PRICE, ORDER_STATUS, ORDER_DATE, SHIP_DATE, SHIP_COUNTRY, PAYMENT_METHOD)
VALUES ('ORD-1011', 'CUST-510', 'Test User', 'test@email.com', 'PROD-101', 'Wireless Bluetooth Headphones', 'Electronics', 1, 79.99, 'Processing', '2025-05-10', NULL, 'United States', 'Credit Card');


--verify the stream is working:
SELECT SYSTEM$STREAM_HAS_DATA('ECOMMERCE_DB.RAW.ORDERS_STREAM');

-- what the stream sees:
SELECT * FROM ECOMMERCE_DB.RAW.ORDERS_STREAM;