-- Create Task 2 — STAGING to ANALYTICS

CREATE TASK IF NOT EXISTS ECOMMERCE_DB.RAW.TASK_STAGING_TO_ANALYTICS
  WAREHOUSE = ECOMMERCE_WH
  AFTER ECOMMERCE_DB.RAW.TASK_RAW_TO_STAGING
AS
  BEGIN
    TRUNCATE TABLE ECOMMERCE_DB.ANALYTICS.DAILY_SALES_SUMMARY;
    INSERT INTO ECOMMERCE_DB.ANALYTICS.DAILY_SALES_SUMMARY (ORDER_DATE, TOTAL_ORDERS, TOTAL_REVENUE, AVG_ORDER_VALUE, TOTAL_ITEMS_SOLD)
    SELECT
        ORDER_DATE,
        COUNT(DISTINCT ORDER_ID),
        SUM(TOTAL_AMOUNT),
        AVG(TOTAL_AMOUNT),
        SUM(QUANTITY)
    FROM ECOMMERCE_DB.STAGING.ORDERS_CLEANED
    WHERE ORDER_STATUS != 'CANCELLED'
    GROUP BY ORDER_DATE;

    TRUNCATE TABLE ECOMMERCE_DB.ANALYTICS.PRODUCT_PERFORMANCE;
    INSERT INTO ECOMMERCE_DB.ANALYTICS.PRODUCT_PERFORMANCE (PRODUCT_ID, PRODUCT_NAME, CATEGORY, TOTAL_QUANTITY_SOLD, TOTAL_REVENUE, TOTAL_ORDERS)
    SELECT
        PRODUCT_ID,
        PRODUCT_NAME,
        CATEGORY,
        SUM(QUANTITY),
        SUM(TOTAL_AMOUNT),
        COUNT(DISTINCT ORDER_ID)
    FROM ECOMMERCE_DB.STAGING.ORDERS_CLEANED
    WHERE ORDER_STATUS != 'CANCELLED'
    GROUP BY PRODUCT_ID, PRODUCT_NAME, CATEGORY;

    TRUNCATE TABLE ECOMMERCE_DB.ANALYTICS.CUSTOMER_SUMMARY;
    INSERT INTO ECOMMERCE_DB.ANALYTICS.CUSTOMER_SUMMARY (CUSTOMER_ID, CUSTOMER_NAME, EMAIL, TOTAL_ORDERS, TOTAL_SPENT, AVG_ORDER_VALUE, FIRST_ORDER_DATE, LAST_ORDER_DATE)
    SELECT
        CUSTOMER_ID,
        CUSTOMER_NAME,
        EMAIL,
        COUNT(DISTINCT ORDER_ID),
        SUM(TOTAL_AMOUNT),
        AVG(TOTAL_AMOUNT),
        MIN(ORDER_DATE),
        MAX(ORDER_DATE)
    FROM ECOMMERCE_DB.STAGING.ORDERS_CLEANED
    WHERE ORDER_STATUS != 'CANCELLED'
    GROUP BY CUSTOMER_ID, CUSTOMER_NAME, EMAIL;
  END;


  SHOW TASKS IN SCHEMA ECOMMERCE_DB.RAW;