--Table 1: Daily Sales Summary

CREATE TABLE IF NOT EXISTS ECOMMERCE_DB.ANALYTICS.DAILY_SALES_SUMMARY
(
    ORDER_DATE  DATE,
    TOTAL_ORDERS    INT,
    TOTAL_REVENUE NUMBER(14,2),
    AVG_ORDER_VALUE NUMBER(10,2),
    TOTAL_ITEMS_SOLD    INT,
    LAST_UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = "Daily aggregated sales metrics for dashboard";


-- Table 2: Product Performance
CREATE TABLE IF NOT EXISTS ECOMMERCE_DB.ANALYTICS.PRODUCT_PERFORMANCE (
    PRODUCT_ID          VARCHAR(50),
    PRODUCT_NAME        VARCHAR(300),
    CATEGORY            VARCHAR(100),
    TOTAL_QUANTITY_SOLD INT,
    TOTAL_REVENUE       NUMBER(14,2),
    TOTAL_ORDERS        INT,
    LAST_UPDATED_AT     TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Product-level sales performance metrics';

--Table 3: Customer Summary
CREATE TABLE IF NOT EXISTS ECOMMERCE_DB.ANALYTICS.CUSTOMER_SUMMARY (
    CUSTOMER_ID         VARCHAR(50),
    CUSTOMER_NAME       VARCHAR(200),
    EMAIL               VARCHAR(200),
    TOTAL_ORDERS        INT,
    TOTAL_SPENT         NUMBER(14,2),
    AVG_ORDER_VALUE     NUMBER(10,2),
    FIRST_ORDER_DATE    DATE,
    LAST_ORDER_DATE     DATE,
    LAST_UPDATED_AT     TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Customer lifetime value and ordering behavior';

--VERIFY ALL 3 TABLES EXIST:
SHOW TABLES IN SCHEMA ECOMMERCE_DB.ANALYTICS;