--Action 1: Resume both tasks
--Resume child task FIRST (Task 2):
ALTER TASK ECOMMERCE_DB.RAW.TASK_STAGING_TO_ANALYTICS RESUME;

--Then resume the root task (Task 1):
ALTER TASK ECOMMERCE_DB.RAW.TASK_RAW_TO_STAGING RESUME;

--Action 2: Don't wait 5 minutes — manually trigger a test run
EXECUTE TASK ECOMMERCE_DB.RAW.TASK_RAW_TO_STAGING;

--Action 3-- Check STAGING got the data:---
SELECT COUNT(*) FROM ECOMMERCE_DB.STAGING.ORDERS_CLEANED;

----Check ANALYTICS tables:----
SELECT * FROM ECOMMERCE_DB.ANALYTICS.DAILY_SALES_SUMMARY;
SELECT * FROM ECOMMERCE_DB.ANALYTICS.PRODUCT_PERFORMANCE;
SELECT * FROM ECOMMERCE_DB.ANALYTICS.CUSTOMER_SUMMARY;

----Action 4: Check task history to confirm both ran successfully--
SELECT NAME, STATE, SCHEDULED_TIME, COMPLETED_TIME, ERROR_MESSAGE
FROM TABLE(ECOMMERCE_DB.INFORMATION_SCHEMA.TASK_HISTORY(
    TASK_NAME => 'TASK_RAW_TO_STAGING',
    SCHEDULED_TIME_RANGE_START => DATEADD(HOUR, -1, CURRENT_TIMESTAMP())
))
ORDER BY SCHEDULED_TIME DESC
LIMIT 5;


SELECT COUNT(*) FROM ECOMMERCE_DB.STAGING.ORDERS_CLEANED




