SELECT * FROM ECOMMERCE_DB.ANALYTICS.V_EXECUTIVE_DASHBOARD;

SELECT * FROM ECOMMERCE_DB.ANALYTICS.V_SALES_TREND;

SELECT * FROM ECOMMERCE_DB.ANALYTICS.V_TOP_PRODUCTS;

SELECT * FROM ECOMMERCE_DB.ANALYTICS.V_CUSTOMER_INSIGHTS;

SELECT * FROM ECOMMERCE_DB.ANALYTICS.V_SALES_BY_COUNTRY;