--View 1: Executive Dashboard KPIs
CREATE OR REPLACE VIEW ECOMMERCE_DB.ANALYTICS.V_EXECUTIVE_DASHBOARD AS
SELECT
    COUNT(DISTINCT o.ORDER_ID) AS TOTAL_ORDERS,
    SUM(o.TOTAL_AMOUNT) AS TOTAL_REVENUE,
    ROUND(AVG(o.TOTAL_AMOUNT), 2) AS AVG_ORDER_VALUE,
    COUNT(DISTINCT o.CUSTOMER_ID) AS UNIQUE_CUSTOMERS,
    COUNT(DISTINCT o.PRODUCT_ID) AS UNIQUE_PRODUCTS,
    MIN(o.ORDER_DATE) AS FIRST_ORDER_DATE,
    MAX(o.ORDER_DATE) AS LAST_ORDER_DATE
FROM ECOMMERCE_DB.STAGING.ORDERS_CLEANED o
WHERE o.ORDER_STATUS != 'CANCELLED';

--View 2: Daily Sales Trend (for line charts)
CREATE OR REPLACE VIEW ECOMMERCE_DB.ANALYTICS.V_SALES_TREND AS
SELECT
    ORDER_DATE,
    TOTAL_ORDERS,
    TOTAL_REVENUE,
    AVG_ORDER_VALUE,
    TOTAL_ITEMS_SOLD,
    SUM(TOTAL_REVENUE) OVER (ORDER BY ORDER_DATE) AS CUMULATIVE_REVENUE
FROM ECOMMERCE_DB.ANALYTICS.DAILY_SALES_SUMMARY
ORDER BY ORDER_DATE;


--View 3: Top Products (for bar charts)
CREATE OR REPLACE VIEW ECOMMERCE_DB.ANALYTICS.V_TOP_PRODUCTS AS
SELECT
    PRODUCT_NAME,
    CATEGORY,
    TOTAL_QUANTITY_SOLD,
    TOTAL_REVENUE,
    TOTAL_ORDERS,
    ROUND(TOTAL_REVENUE / NULLIF(TOTAL_QUANTITY_SOLD, 0), 2) AS AVG_PRICE_PER_UNIT
FROM ECOMMERCE_DB.ANALYTICS.PRODUCT_PERFORMANCE
ORDER BY TOTAL_REVENUE DESC;

--View 4: Customer Insights (for tables/segmentation)
CREATE OR REPLACE VIEW ECOMMERCE_DB.ANALYTICS.V_CUSTOMER_INSIGHTS AS
SELECT
    CUSTOMER_NAME,
    EMAIL,
    TOTAL_ORDERS,
    TOTAL_SPENT,
    AVG_ORDER_VALUE,
    FIRST_ORDER_DATE,
    LAST_ORDER_DATE,
    DATEDIFF('day', FIRST_ORDER_DATE, LAST_ORDER_DATE) AS CUSTOMER_TENURE_DAYS,
    CASE
        WHEN TOTAL_SPENT >= 200 THEN 'HIGH VALUE'
        WHEN TOTAL_SPENT >= 100 THEN 'MEDIUM VALUE'
        ELSE 'LOW VALUE'
    END AS CUSTOMER_SEGMENT
FROM ECOMMERCE_DB.ANALYTICS.CUSTOMER_SUMMARY
ORDER BY TOTAL_SPENT DESC;

--View 5: Sales by Country (for maps)
CREATE OR REPLACE VIEW ECOMMERCE_DB.ANALYTICS.V_SALES_BY_COUNTRY AS
SELECT
    SHIP_COUNTRY,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE,
    ROUND(AVG(TOTAL_AMOUNT), 2) AS AVG_ORDER_VALUE
FROM ECOMMERCE_DB.STAGING.ORDERS_CLEANED
WHERE ORDER_STATUS != 'CANCELLED'
GROUP BY SHIP_COUNTRY
ORDER BY TOTAL_REVENUE DESC;

----VERIFY ALL VIEW:---
SHOW VIEWS IN SCHEMA ECOMMERCE_DB.ANALYTICS;