EXECUTE TASK ECOMMERCE_DB.RAW.TASK_RAW_TO_STAGING;

--Checking all layers:
SELECT COUNT(*) FROM ECOMMERCE_DB.STAGING.ORDERS_CLEANED;
SELECT COUNT(*) FROM ECOMMERCE_DB.ANALYTICS.DAILY_SALES_SUMMARY;
SELECT COUNT(*) FROM ECOMMERCE_DB.ANALYTICS.PRODUCT_PERFORMANCE;
SELECT COUNT(*) FROM ECOMMERCE_DB.ANALYTICS.CUSTOMER_SUMMARY;